# compose files for the firewall exercise.

version: "3"

services:
  kali:
    image: registry.gitlab.com/xandfury/containers/firewall:attacker
    container_name: kali-10.29.107.5-fw
    hostname: kali-10-29-107-5-fw
    tty: true
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net-10.29.107.0:
        ipv4_address: 10.29.107.5
    depends_on:
      - host1
      - host2
      - host3
      - hostn
    extra_hosts:
      - "host1:192.168.90.5"
      - "host2:192.168.90.6"
      - "host3:192.168.90.7"
      - "hostN:192.168.90.234"

  other-user:
    image: registry.gitlab.com/xandfury/containers/firewall:host1
    container_name: other-user-10.29.107.24-fw
    hostname: other-user-10-29-107-24-fw
    tty: true
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net-10.29.107.0:
        ipv4_address: 10.29.107.24
    depends_on:
      - host1
      - host2
      - host3
      - hostn
    extra_hosts:
      - "host1:192.168.90.5"
      - "host2:192.168.90.6"
      - "host3:192.168.90.7"
      - "hostN:192.168.90.234"
      

  host1:
    image: registry.gitlab.com/xandfury/containers/firewall:host1
    container_name: host1-192.168.90.5-fw
    hostname: host1-192-168-90-5-fw
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.90.0:
        ipv4_address: 192.168.90.5
    command: bash -c "/host1.sh"
    depends_on:
      - router
    extra_hosts:
      - "attacker:192.168.90.5"
      - "other-user:10.29.107.24"
      


  host2:
    image: registry.gitlab.com/xandfury/containers/firewall:host2
    container_name: host2-192.168.90.6-fw
    hostname: host2-192-168-90-6-fw
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.90.0:
        ipv4_address: 192.168.90.6
    depends_on:
      - router
    extra_hosts:
      - "attacker:192.168.90.5"
      - "other-user:10.29.107.24"

  host3:
    image: registry.gitlab.com/xandfury/containers/firewall:host3
    container_name: host3-192.168.90.7-fw
    hostname: host3-192-168-90-7-fw
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.90.0:
        ipv4_address: 192.168.90.7
        aliases:
          - ftp
          - terrible-ftp
    depends_on:
      - router
    extra_hosts:
      - "attacker:192.168.90.5"
      - "other-user:10.29.107.24"

  hostn:
    image: registry.gitlab.com/xandfury/containers/firewall:hostN
    container_name: hostN-192.168.90.234-fw
    hostname: hostN-192-168-90-234-fw
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.90.0:
        ipv4_address: 192.168.90.234
    depends_on:
      - router
    extra_hosts:
      - "attacker:192.168.90.5"
      - "other-user:10.29.107.24"

  router:
    image: registry.gitlab.com/xandfury/containers/firewall:router
    container_name: router-10.29.107.11-fw
    hostname: router-fw
    tty: true
    environment:
      - DEPLOY_EX=2
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./logs-ex-2:/var/log/ulog/
    networks:
      net-10.29.107.0:
        ipv4_address: 10.29.107.11
      net-192.168.90.0:
        ipv4_address: 192.168.90.11
    command: bash -c "/start_router.sh"

networks:
  net-192.168.90.0:
    ipam:
      config:
        - subnet: 192.168.90.0/24

  net-10.29.107.0:
    ipam:
      config:
        - subnet: 10.29.107.0/24